# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyteams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.IntegerField(choices=[('tech', 'tech'), ('management', 'management'), ('marketing', 'marketing')], max_length=10),
        ),
    ]
